spring:
  mail:
    host: smtp.dizver.com
    port: 25
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kms?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: bc14431945!
    #password: gksrnrzmf+10@%
  jpa:
    hibernate:
      ddl-auto: none #create #none # # update #
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 80
